# This file specifies your Python application's runtime configuration.
# See https://cloud.google.com/appengine/docs/managed-vms/python/runtime
# for details.

runtime: python
# vm: true
env: flex
entrypoint: gunicorn -b :$PORT main:app -t 90
# entrypoint: gunicorn -b :$PORT main:app -t 60

runtime_config:
  python_version: 3
# handlers:
# - url: /favicon\.ico
#   static_files: static/images/favicon.ico
#   upload: static/images/favicon\.ico

#beta_settings:
    # If using Cloud SQL, uncomment and set this value to the Cloud SQL
    # connection name, e.g.
    #   "project:region:cloudsql-instance"
    # You must also update the values in config.py.
    #
    # cloud_sql_instances: "your-cloudsql-connection-name"
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
#  cool_down_period_sec: 120 # default value
#  cpu_utilization:
#    target_utilization: 0.5


